# See https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17, 21, 25]
        include:
        - os: macos-15-intel
          java: 17
      fail-fast: false
    steps:
    - name: Checkout sources
      uses: actions/checkout@v7

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'

    - name: Build
      run: mvn -B package javadoc:javadoc

    timeout-minutes: 150
